name: PR Checks

on:
  pull_request:
    branches: [main, dev]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint && npm run lint:css && npm run format

      - name: Typecheck
        run: npm run build:types

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
